name = "zipper-manual"
defaultTargets = ["Docs", "docs"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.24.0"

[[lean_lib]]
name = "Docs"

[[lean_exe]]
name = "docs"
root = "Main"
